### ISSUE TITLE
Retain existing node to handle angle

### ISSUE THREAD

**Issue by gorjious** [pkolchanov/HarmonicMove#1]
First off – excellent plug-in! I am certain it will join the arsenal of harmonizing plugins.

My only suggestion would be to retain the angle between a node and handle (especially if it is a green smooth curve) that way it would be much easier to select a handle and with one hand be able to harness the power of the plugin (I know holding shift would lock it vertical/horizontal but I think if the plugin retains existing angles, it will make it easier for the user to focus only on the relevant changes)

https://user-images.githubusercontent.com/23149420/174592538-5882c2cb-b614-44ff-8b88-ce2583928659.mov

**Comment by pkolchanov** [comment]
Hello, Gor. 
Thank you for your feedback :) 

I'll take a look on it.

**Comment by pkolchanov** [comment]
Hi, Gor! 
Sorry for the long reply (two years 😱)

I've fixed it in the 2a2de4c
![Screen Recording 2024-06-26 at 11 18 14](https://github.com/pkolchanov/HarmonicMove/assets/6161120/70b38940-03f7-4694-b68a-b68f173c66ec)
