### ISSUE TITLE
Consider addig the icon tool at the end of the list

### ISSUE THREAD

**Issue by laepage** [pkolchanov/HarmonicMove#4]
Tthe plugin/tool is working perfectly, I have an UI issue! Please, consider adding the icon at the right end of the toolbar. I find somewhat obtrusive that Harmoninc Move appears between two core Glyphs tools, Lasso and Draw. All the other "extra" plugin's icons are placed and the right side of the bar, like Supertool, LttrInk, Gauge Tool etc.

**Comment by pkolchanov** [comment]
Hi, @laepage!

Thank you for your feedback. Fixed in 51718a2343eb40e5f86bb77de87d46a4e8d99e5d. 
Please, update the plugin with the plugin manager.
