### ISSUE TITLE
traceback from user

### ISSUE THREAD

**Issue by schriftgestalt** [pkolchanov/HarmonicMove#5]
Traceback (most recent call last):

File "plugin.py", line 146, in moveSelectionWithPoint_withModifier_
node, N, NN, P, PP = find_selected_node(layer)
^^^^^^^^^^^^^^^^^^^^^^^^^

File "plugin.py", line 62, in find_selected_node
return (node, node.nextNode, node.nextNode.nextNode, node.prevNode, node.prevNode.prevNode)
^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'prevNode'

App:3.3-3310 Plugin:1-1 System:14.5.0

**Comment by pkolchanov** [comment]
Fixed in the d8dda9bbcc4ff0c099c06c60346bcc0598a36c9c

Thank you for the report!
